### ISSUE TITLE
Use react-native component in Main page

### ISSUE THREAD

**Issue by wupeng191** [wallchainfoundation/wallet#31]
Old tab compoment is react-native-tab-navigator, we will use react-native createMaterialBottomTabNavigator replace it.

**Comment by somewhereMrli** [comment]
Done at PR #34 
[ISSUE-31.001.patch.txt](https://github.com/wallchainfoundation/wallet/files/2426882/ISSUE-31.001.patch.txt)

**Comment by somewhereMrli** [comment]
Done at PR #35 
[ISSUE-31.001.patch.txt](https://github.com/wallchainfoundation/wallet/files/2426997/ISSUE-31.001.patch.txt)

**Comment by wupeng191** [comment]
Ok, it's done.
