### ISSUE TITLE
Update function list for Profile page

### ISSUE THREAD

**Issue by wupeng191** [wallchainfoundation/wallet#32]
Function list:

1. Name
2. Address
3. Reset Password
4. Export PK
5. Export keystore
6. About
7. Settings

**Comment by somewhereMrli** [comment]
Done at PR #38 
[ISSUE-32.001.patch.txt](https://github.com/wallchainfoundation/wallet/files/2428392/ISSUE-32.001.patch.txt)

**Comment by wupeng191** [comment]
Ok. it's done.
