### ISSUE TITLE
Add function for reset password

### ISSUE THREAD

**Issue by wupeng191** [wallchainfoundation/wallet#33]
Reset password and replace local storage.

1. input old password to validate
2. input new password
3. confirm new password

**Comment by somewhereMrli** [comment]
Done at PR #41 
[ISSUE-33.001.patch.txt](https://github.com/wallchainfoundation/wallet/files/2433026/ISSUE-33.001.patch.txt)

**Comment by somewhereMrli** [comment]
Done at PR #53 
[ISSUE-33.001.patch.txt](https://github.com/wallchainfoundation/wallet/files/2453742/ISSUE-33.001.patch.txt)

**Comment by somewhereMrli** [comment]
Done at PR #55 
[ISSUE-33.001.patch.txt](https://github.com/wallchainfoundation/wallet/files/2453860/ISSUE-33.001.patch.txt)

**Comment by oncecrossover** [comment]
Ok,it's done.
