### ISSUE TITLE
The new page should be cover the tab page in Main page

### ISSUE THREAD

**Issue by wupeng191** [wallchainfoundation/wallet#36]
The new page should be cover the tab page in Main page, click arrow button to back Main page.
By the way，replace tab icon with new UI design.

![1](https://user-images.githubusercontent.com/8652248/46193410-a6422780-c330-11e8-8b2b-e2a48ff54053.png)

**Comment by somewhereMrli** [comment]
Done at PR #58 
[ISSUE-37.001.patch.txt](https://github.com/wallchainfoundation/wallet/files/2458523/ISSUE-37.001.patch.txt)

**Comment by oncecrossover** [comment]
Ok, it's done.
