### ISSUE TITLE
Set a wallet name in Profile page

### ISSUE THREAD

**Issue by wupeng191** [wallchainfoundation/wallet#37]
Set a wallet name and save to local storage.
Using CurrentWallet global object.

**Comment by somewhereMrli** [comment]
Done at PR #58 
[ISSUE-37.001.patch.txt](https://github.com/wallchainfoundation/wallet/files/2458526/ISSUE-37.001.patch.txt)

**Comment by oncecrossover** [comment]
Ok, it's done.
