### ISSUE TITLE
Add license disclaimer in head of all files.

### ISSUE THREAD

**Issue by edsburke** [wallchainfoundation/wallet#44]
LGPL is used for wallet project. License disclaimer should be added to all files.

See also:

/**
 * Wallchain
 * Copyright 2018-Present The Wallchain Foundation
 *
 * This product includes software developed at The Wallchain Foundation.
 *
 * This file is part of the Wallchain library.
 * The Wallchain library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * The Wallchain library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License
 * along with the Wallchain library. If not, see <http://www.gnu.org/licenses/>.
 */

**Comment by oncecrossover** [comment]
Done at PR #57.
