### ISSUE TITLE
Add detail and password confirm step for transaction

### ISSUE THREAD

**Issue by oncecrossover** [wallchainfoundation/wallet#61]
1.Click next button to show transaction detail.
2.Click confirm button to input password.

**Comment by somowhere** [comment]
Done at PR #65 
[ISSUE-61.001.patch.txt](https://github.com/wallchainfoundation/wallet/files/2476309/ISSUE-61.001.patch.txt)

**Comment by oncecrossover** [comment]
Please show transaction detail before input password.

**Comment by somowhere** [comment]
Done at PR #70 
[ISSUE-61.001.patch.txt](https://github.com/wallchainfoundation/wallet/files/2483165/ISSUE-61.001.patch.txt)

**Comment by somowhere** [comment]
Done at PR #71 
[ISSUE-61.002.patch.txt](https://github.com/wallchainfoundation/wallet/files/2487222/ISSUE-61.002.patch.txt)

**Comment by oncecrossover** [comment]
Ok, it's done.
