### ISSUE TITLE
Update button text for Deposit and Withdraw

### ISSUE THREAD

**Issue by oncecrossover** [wallchainfoundation/wallet#64]
1.Deposit should be Receive.
2.Withdraw should be Send.

**Comment by somowhere** [comment]
Done at PR #72 
[ISSUE-64.001.patch.txt](https://github.com/wallchainfoundation/wallet/files/2495105/ISSUE-64.001.patch.txt)

**Comment by oncecrossover** [comment]
Ok, it's done.
