### ISSUE TITLE
Update tab icon style in Main.js

### ISSUE THREAD

**Issue by oncecrossover** [wallchainfoundation/wallet#73]
Seem like the below picture:

![image](https://user-images.githubusercontent.com/43728891/47209455-f86fe900-d3c2-11e8-9840-65ae6be10ab6.png)

**Comment by somewhereMrli** [comment]
Done at PR #75 
[ISSUE-73.001.patch.txt](https://github.com/wallchainfoundation/wallet/files/2503980/ISSUE-73.001.patch.txt)

**Comment by oncecrossover** [comment]
Ok, it's done.
